name: Deploy To Heroku

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Compile To Minified Version
        run: yarn compile

      - name: Copy Package.json
        run: |
          cp package.json bot/package.json

      - name: Add Procfile
        run: |
          echo "worker: node index.js" > bot/Procfile

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: release # The branch the action should deploy to.
          folder: bot # The folder the action should deploy.
