name: tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test TypeScript Build
        run: |
          yarn temp:check-tsc

      # - name: Install Dependencies
      #   run: |
      #     yarn

      # - name: Run Tests
      #   run: |
      #     yarn test:cov

      # - name: Colect Coverage
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      #   uses: coverallsapp/github-action@v1.1.2
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
